### PR TITLE
Reconstructed navbar

### PR DESCRIPTION
**Pull request by P1wko**
- Hover effect with transmitions
- Sticky navbar
- Active element on scroll highlighted
- Hamburger menu on smaller windows

### CODE REVIEW

**Comment by Gumbosh** [comment]
In mobile view, I would move the padding from the li element to the anchor tag and add display:block to make it easier for users to click on navigation.

**Comment by marcinstenka** [comment]
I would reconsider border top on nav element

**Comment by P1wko** [comment]
> I would reconsider border top on nav element

Done, removed

**Comment by P1wko** [comment]
> In mobile view, I would move the padding from the li element to the anchor tag and add display:block to make it easier for users to click on navigation.

Done

**Review by marcinstenka — APPROVED** [review]

**Review by Gumbosh — APPROVED** [review]

**Review by MateuszBukowski93 — APPROVED** [review]

**Pull request merged**
